import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import "./globals.css";
import localFont from "next/font/local";
import { auth } from "../../auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const HelveticaNeue = localFont({
  src: [
    {
      path: "./font/HelveticaNeueRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/HelveticaNeueMedium.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./font/HelveticaNeueBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./font/HelveticaNeueBold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./font/HelveticaNeueBlack.otf",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" className="h-full">
        <body className="h-full antialiased">
          <Toaster position="bottom-center" richColors />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
